version: '3.4'
services:
  cv_worker:
    build:
      network: host
      context: ./cv_worker
      dockerfile: Dockerfile
    environment:
      PORT: '5000'
      MODE: production
    depends_on:
      - file_server
    ports:
      - '5000:5000'
    volumes:
      - ./assets:/opt/assets

  file_server:
    build:
      context: ./fileServer
      dockerfile: Dockerfile
    environment:
      PORT: '8081'
      NODE_ENV: production
    ports:
      - '8081:8081'
    volumes:
      - ./assets:/opt/assets

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - file_server
      - cv_worker
    ports:
      - '3000:80'
    # links:
    #   - cv_worker
