version: '3.4'
services:
  cv_worker:
    build:
      context: ./cv_worker
      dockerfile: Dockerfile
    environment:
      - PORT: 6300
      - MODE: production
    depends_on:
      - file_server
    ports:
      - '6300:6300'
    volumes:
      - ./assets:/opt/assets

  file_server:
    build:
      context: ./fileServer
      dockerfile: Dockerfile
    environment:
      - PORT: 8081
      - NODE_ENV: production
    ports:
      - '8081:8081'
    volumes:
      - ./assets:/opt/assets

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - file_server
      - cv_worker
    environment:
      - SOCKET_PORT: 6300
    ports:
      - '3000:80'
