version: '3.4'
services:
  cv_worker:
    build:
      context: ./cv_worker
      dockerfile: Dockerfile
    environment:
      PORT: '5000'
      MODE: production
    depends_on:
      - file_server
    ports:
      - '5000:5000'
    volumes:
      - ./assets:/opt/assets

  file_server:
    build:
      context: ./fileServer
      dockerfile: Dockerfile
    environment:
      PORT: '8081'
      NODE_ENV: production
    ports:
      - '8081:8081'
    volumes:
      - ./assets:/opt/assets

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - file_server
      - cv_worker
    ports:
      - '3000:80'
    restart: always
    # links:
    #   - cv_worker

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    command: npx cypress run --config video=false
    depends_on:
      - client
    environment:
      CYPRESS_baseUrl: 'http://client'
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
