export default Object.freeze({
  SET_GRAY: "SET_GRAY",
  SET_COLOR: "SET_COLOR",
  SET_REQUESTED_IMAGE: "SET_REQUESTED_IMAGE",
  SET_REQUESTED_IMAGE_AVAILABLE: "SET_IMAGE_AVAILABLE",
  RESET: "RESET",
  PROCESS: "PROCESS"
});
